POST http://localhost:5000/api/services
Content-Type: application/json

{
    "name": "Algum Serviço",
    "description": "Exemplo de descrição",
    "price": 1400,
    "image": "https://uauposters.com.br/media/catalog/product/cache/1/thumbnail/800x930/9df78eab33525d08d6e5fb8d27136e95/1/9/199020140605-199020140605-uau-posters-filmes-todo-poderoso-2--evan-almighty-.jpg" 
}

